version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: api_project/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
